Import('env')

env = env.Clone()

#env['CPATH'] +=  []
#env['CPPPATH'] = env['CPATH']
env['LIBS'] += ['webgraph', 'boost_regex', 'boost_program_options', 'boost_filesystem', 'boost_system']

env.Program(target="compress_webgraph", source = ["compress_webgraph.cpp"])
env.Program(target="print_webgraph", source = ["print_webgraph.cpp"])
